
/*******************************************************************************
    Verilog netlist generated by IPGEN Lattice Radiant Software (64-bit)
    2025.2.0.48.0
    Soft IP Version: 1.2.0
    2026 01 22 11:22:50
*******************************************************************************/
/*******************************************************************************
    Wrapper Module generated per user settings.
*******************************************************************************/
(* ORIG_MODULE_NAME="efb_flash_i2c", LATTICE_IP_GENERATED="1" *) module efb_flash_i2c (wb_clk_i, 
        wb_rst_i, 
        wb_cyc_i, 
        wb_stb_i, 
        wb_we_i, 
        wb_adr_i, 
        wb_dat_i, 
        wb_dat_o, 
        wb_ack_o, 
        i2c1_irqo, 
        wbc_ufm_irq, 
        i2c1_scl, 
        i2c1_sda) ;
    input wb_clk_i ; 
    input wb_rst_i ; 
    input wb_cyc_i ; 
    input wb_stb_i ; 
    input wb_we_i ; 
    input [7:0] wb_adr_i ; 
    input [7:0] wb_dat_i ; 
    output [7:0] wb_dat_o ; 
    output wb_ack_o ; 
    output i2c1_irqo ; 
    output wbc_ufm_irq ; 
    inout i2c1_scl ; 
    inout i2c1_sda ; 
    efb_flash_i2c_ipgen_lscc_efb #(.FAMILY("LFMXO4"),
            .DEVICE("LFMXO4-025HC"),
            .DEV_DENSITY("025"),
            .DEVICE_ID_TB(19607619),
            .EFB_WB_IN(1),
            .EFB_INTERFACE_IN("WISHBONE"),
            .EFB_WB_CLK_FREQ_TB(50.0),
            .EFB_WB_CLK_FREQ("50.0"),
            .EFB_I2C1_CFG_TB("I2C1_USER"),
            .EFB_I2C1("ENABLED"),
            .EFB_I2C2("DISABLED"),
            .EFB_SPI("DISABLED"),
            .EFB_TC("DISABLED"),
            .EFB_TC_PORTMODE("NO_WB"),
            .EFB_PLL_IN(0),
            .EFB_PLL_NUM_IN(1),
            .EFB_UFM("ENABLED"),
            .I2C1_GEN_CALL("DISABLED"),
            .I2C1_WAKEUP("DISABLED"),
            .I2C1_BUS_PERF("400kHz"),
            .I2C1_CLK_DIVIDER("32"),
            .I2C1_ADDRESSING("7BIT"),
            .I2C1_SLAVE_ADDR("0b1000001"),
            .I2C2_GEN_CALL("DISABLED"),
            .I2C2_WAKEUP("DISABLED"),
            .I2C2_BUS_PERF("100kHz"),
            .I2C2_CLK_DIVIDER("125"),
            .I2C2_ADDRESSING("7BIT"),
            .I2C2_SLAVE_ADDR("0b1000010"),
            .SPI_MODE("SLAVE"),
            .SPI_WAKEUP("DISABLED"),
            .SPI_CLK_DIVIDER("50"),
            .SPI_CS_NUM(1),
            .SPI_LSB_FIRST("DISABLED"),
            .SPI_CLK_INV("DISABLED"),
            .SPI_PHASE_ADJ("DISABLED"),
            .SPI_SLAVE_HANDSHAKE("DISABLED"),
            .SPI_INTR_TXRDY("DISABLED"),
            .SPI_INTR_RXRDY("DISABLED"),
            .SPI_INTR_TXOVR("DISABLED"),
            .SPI_INTR_RXOVR("DISABLED"),
            .TC_MODE("CTCM"),
            .TC_OC_MODE("TOGGLE"),
            .TC_RESETN("ENABLED"),
            .TC_SCLK_SEL("PCLOCK"),
            .TC_CCLK_SEL("1"),
            .TC_OV_INT("OFF"),
            .TC_OCR_INT("OFF"),
            .TC_ICR_INT("OFF"),
            .TC_TOP_SEL("OFF"),
            .TC_TOP_SET("65535"),
            .TC_OCR_SET("32767"),
            .UFM_INIT_PAGES("1"),
            .UFM_INIT_START_PAGE("638"),
            .UFM_INIT_ALL_ZEROS("ENABLED"),
            .UFM_INIT_FILE_NAME(""),
            .UFM_INIT_FILE_FORMAT("HEX")) lscc_efb_inst (.wb_clk_i(wb_clk_i), 
                .wb_rst_i(wb_rst_i), 
                .wb_cyc_i(wb_cyc_i), 
                .wb_stb_i(wb_stb_i), 
                .wb_we_i(wb_we_i), 
                .wb_adr_i(wb_adr_i[7:0]), 
                .wb_dat_i(wb_dat_i[7:0]), 
                .wb_dat_o(wb_dat_o[7:0]), 
                .wb_ack_o(wb_ack_o), 
                .clk_i(1'b0), 
                .rstn_i(1'b1), 
                .apb_psel_i(1'b0), 
                .apb_paddr_i(8'b00000000), 
                .apb_pwdata_i(8'b00000000), 
                .apb_pwrite_i(1'b0), 
                .apb_penable_i(1'b0), 
                .apb_pready_o(), 
                .apb_prdata_o(), 
                .apb_pslverr_o(), 
                .i2c1_irqo(i2c1_irqo), 
                .i2c2_irqo(), 
                .wbc_ufm_irq(wbc_ufm_irq), 
                .cfg_wake(), 
                .cfg_stdby(), 
                .int_o(), 
                .pll0_ack_i(1'b0), 
                .pll0_dati_i(8'b00000000), 
                .pll0_clk_o(), 
                .pll0_rst_o(), 
                .pll0_addr_o(), 
                .pll0_dato_o(), 
                .pll0_we_o(), 
                .pll0_stb_o(), 
                .pll1_ack_i(1'b0), 
                .pll1_dati_i(8'b00000000), 
                .pll1_clk_o(), 
                .pll1_rst_o(), 
                .pll1_addr_o(), 
                .pll1_dato_o(), 
                .pll1_we_o(), 
                .pll1_stb_o(), 
                .tc_clki(1'b0), 
                .tc_rstn(1'b1), 
                .tc_ic(1'b0), 
                .tc_int(), 
                .tc_oc(), 
                .i2c1_scl(i2c1_scl), 
                .i2c1_sda(i2c1_sda), 
                .i2c2_scl(), 
                .i2c2_sda(), 
                .spi_clk(), 
                .spi_miso(), 
                .spi_mosi(), 
                .spi_csn(), 
                .spi_scsn(1'b1), 
                .spi_irq(), 
                .ufm_sn(1'b1)) ; 
endmodule



`timescale 1ns/1ps
/* >>>>>>>>>>>>>>>>>>>>>>> COPYRIGHT NOTICE <<<<<<<<<<<<<<<<<<<<<<<<<
     ------------------------------------------------------------------
     Copyright (c) 2019-2022 by Lattice Semiconductor Corporation
     ALL RIGHTS RESERVED
     ------------------------------------------------------------------

       IMPORTANT: THIS FILE IS USED BY OR GENERATED BY the LATTICE PROPEL™ DEVELOPMENT SUITE, WHICH INCLUDES PROPEL BUILDER AND PROPEL SDK.

       Lattice grants permission to use this code pursuant to the
       terms of the Lattice Propel License Agreement.

     DISCLAIMER:

       LATTICE MAKES NO WARRANTIES ON THIS FILE OR ITS CONTENTS, WHETHER EXPRESSED, IMPLIED, STATUTORY, OR IN ANY PROVISION OF THE LATTICE PROPEL LICENSE AGREEMENT OR COMMUNICATION WITH LICENSEE, AND LATTICE SPECIFICALLY DISCLAIMS ANY IMPLIED WARRANTY OF MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE.  LATTICE DOES NOT WARRANT THAT THE FUNCTIONS CONTAINED HEREIN WILL MEET LICENSEE'S REQUIREMENTS, OR THAT LICENSEE'S OPERATION OF ANY DEVICE, SOFTWARE OR SYSTEM USING THIS FILE OR ITS CONTENTS WILL BE UNINTERRUPTED OR ERROR FREE, OR THAT DEFECTS HEREIN WILL BE CORRECTED.  LICENSEE ASSUMES RESPONSIBILITY FOR SELECTION OF MATERIALS TO ACHIEVE ITS INTENDED RESULTS, AND FOR THE PROPER INSTALLATION, USE, AND RESULTS OBTAINED THEREFROM.  LICENSEE ASSUMES THE ENTIRE RISK OF THE FILE AND ITS CONTENTS PROVING DEFECTIVE OR FAILING TO PERFORM PROPERLY AND IN SUCH EVENT, LICENSEE SHALL ASSUME THE ENTIRE COST AND RISK OF ANY REPAIR, SERVICE, CORRECTION, OR ANY OTHER LIABILITIES OR DAMAGES CAUSED BY OR ASSOCIATED WITH THE SOFTWARE.  IN NO EVENT SHALL LATTICE BE LIABLE TO ANY PARTY FOR DIRECT, INDIRECT,SPECIAL, INCIDENTAL, OR CONSEQUENTIAL DAMAGES, INCLUDING LOST PROFITS, ARISING OUT OF THE USE OF THIS FILE OR ITS CONTENTS, EVEN IF LATTICE HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES. LATTICE'S SOLE LIABILITY, AND LICENSEE'S SOLE REMEDY, IS SET FORTH ABOVE.  LATTICE DOES NOT WARRANT OR REPRESENT THAT THIS FILE, ITS CONTENTS OR USE THEREOF DOES NOT INFRINGE ON THIRD PARTIES' INTELLECTUAL PROPERTY RIGHTS, INCLUDING ANY PATENT. IT IS THE USER'S RESPONSIBILITY TO VERIFY THE USER SOFTWARE DESIGN FOR CONSISTENCY AND FUNCTIONALITY THROUGH THE USE OF FORMAL SOFTWARE VALIDATION METHODS.

     ------------------------------------------------------------------
 */
//==========================================================================
// Module : apb2wb
//==========================================================================
module efb_flash_i2c_ipgen_lscc_apb2wb #(parameter DATA_WIDTH = 32, 
        parameter ADDR_WIDTH = 32, 
        parameter REG_OUTPUT = 1) (
    //--begin_param--
    //----------------------------
    // Parameters
    //----------------------------
    // Data width
    // Address width
    // enable registered output
    //--end_param--
    //--begin_ports--
    //----------------------------
    // Global Signals (Clock and Reset)
    //----------------------------
    input clk_i,  // apb clock
    input rst_i,  // active high reset
    //----------------------------
    // APB Interface
    //----------------------------
    input apb_penable_i,  // apb enable
    input apb_psel_i,  // apb slave select
    input apb_pwrite_i,  // apb write 1, read 0
    input [(ADDR_WIDTH - 1):0] apb_paddr_i,  // apb address
    input [(DATA_WIDTH - 1):0] apb_pwdata_i,  // apb write data
    output reg apb_pready_o,  // apb ready
    //output reg                    apb_pslverr_o,        // apb slave error
    output reg [(DATA_WIDTH - 1):0] apb_prdata_o,  // apb read data
    //----------------------------
    // Wishbone-Extended Interface
    //----------------------------
    input wb_ack_i,  //lmmi_ready_i,         // slave is ready to start new transaction
    //input                         lmmi_rdata_valid_i,   // read transaction is complete
    //input                         lmmi_error_i,         // error indicator
    input [(DATA_WIDTH - 1):0] wb_dat_i,  //lmmi_rdata_i,         // read data
    (* syn_preserve=1 *) output reg wb_cyc_o, 
    (* syn_preserve=1 *) output reg wb_stb_o, 
    output reg wb_we_o,  //lmmi_wr_rdn_o,        // write 1, read 0
    output reg [(ADDR_WIDTH - 1):0] wb_adr_o,  //lmmi_offset_o,        // address/offset
    output reg [(DATA_WIDTH - 1):0] wb_dat_o //, lmmi_wdata_o,         // write data
        //output wire                   lmmi_resetn_o         // reset to LMMI inteface
        ) ;
    //--end_ports--
    //--------------------------------------------------------------------------
    //--- Local Parameters/Defines ---
    //--------------------------------------------------------------------------
    localparam ST_BUS_IDLE = 2'd0 ; 
    localparam ST_BUS_REQ = 2'd1 ; 
    localparam ST_BUS_DAT = 2'd2 ; 
    localparam ST_BUS_WAIT = 2'd3 ; 
    //--------------------------------------------------------------------------
    //--- Combinational Wire/Reg ---
    //--------------------------------------------------------------------------
    //reg                           timeout_flag_nxt;
    //reg         [7:0]             req_timer_nxt;
    //--------------------------------------------------------------------------
    //--- Registers ---
    //--------------------------------------------------------------------------
    //reg                           timeout_flag;
    //reg         [7:0]             req_timer;
    //assign lmmi_resetn_o =  rst_i;
    generate
        if (REG_OUTPUT) 
            begin : genblk1
                reg [1:0] bus_sm_ns ; 
                reg [1:0] bus_sm_cs ; 
                reg wb_stb_nxt ; 
                reg wb_cyc_nxt ; 
                reg wb_we_nxt ; 
                reg [(ADDR_WIDTH - 1):0] wb_adr_nxt ; 
                reg [(DATA_WIDTH - 1):0] wb_dat_nxt ; 
                reg apb_pready_nxt ; 
                // reg                           apb_pslverr_nxt ;
                reg [(DATA_WIDTH - 1):0] apb_prdata_nxt ; 
                //--------------------------------------------
                //-- Bus Statemachine --
                //--------------------------------------------
                always
                    @(*)
                    begin
                        bus_sm_ns = bus_sm_cs ;
                        case (bus_sm_cs)
                        ST_BUS_REQ : 
                            begin
                                if (wb_ack_i) 
                                    begin
                                        if (wb_we_o) 
                                            begin
                                                bus_sm_ns = ST_BUS_WAIT ;
                                            end
                                        else
                                            begin
                                                if ((!wb_we_o)) 
                                                    bus_sm_ns = ST_BUS_WAIT ;
                                                else
                                                    bus_sm_ns = ST_BUS_DAT ;
                                            end
                                    end
                                else
                                    begin
                                        //if(timeout_flag) begin
                                        //  bus_sm_ns   = ST_BUS_WAIT;
                                        //end
                                        //else begin
                                        bus_sm_ns = ST_BUS_REQ ;
                                        //end
                                    end
                            end
                        ST_BUS_DAT : 
                            begin
                                if ((!wb_we_o)) 
                                    bus_sm_ns = ST_BUS_WAIT ;
                                else
                                    begin
                                        //if(timeout_flag)
                                        // bus_sm_ns = ST_BUS_WAIT;
                                        //else
                                        bus_sm_ns = ST_BUS_DAT ;
                                    end
                            end
                        ST_BUS_WAIT : 
                            begin
                                bus_sm_ns = ST_BUS_IDLE ;
                            end
                        default : 
                            begin
                                if (apb_psel_i) 
                                    bus_sm_ns = ST_BUS_REQ ;
                                else
                                    bus_sm_ns = ST_BUS_IDLE ;
                            end
                        endcase 
                    end//--always @*--
                //--------------------------------------------
                //-- APB to WB conversion --
                //--------------------------------------------	
                always
                    @(*)
                    begin
                        wb_cyc_nxt = wb_cyc_o ;
                        wb_stb_nxt = wb_stb_o ;
                        wb_we_nxt = wb_we_o ;
                        wb_adr_nxt = wb_adr_o ;
                        wb_dat_nxt = wb_dat_o ;
                        apb_pready_nxt = apb_pready_o ;
                        //apb_pslverr_nxt  = 1'b0;
                        apb_prdata_nxt = apb_prdata_o ;
                        //req_timer_nxt    = req_timer + {7'd0,~timeout_flag};
                        //timeout_flag_nxt = &req_timer[7:1];
                        case (bus_sm_cs)
                        ST_BUS_REQ : 
                            begin
                                if (wb_ack_i) 
                                //else if(timeout_flag) begin
                                //  wb_cyc_nxt = 1'b0;
                                //  wb_stb_nxt = 1'b0;
                                //  wb_we_nxt = 1'b0;
                                //  if(wb_we_o) begin
                                //    apb_pready_nxt   = 1'b1;
                                //  end
                                //  else begin
                                //    apb_pready_nxt  = 1'b1;
                                //    apb_prdata_nxt  = 32'd0;
                                //    //apb_pslverr_nxt = 1'b1;
                                //  end
                                //end // timeout_flag
                                    begin
                                        wb_cyc_nxt = 1'b0 ;
                                        wb_stb_nxt = 1'b0 ;
                                        wb_we_nxt = 1'b0 ;
                                        if (wb_we_o) 
                                            begin
                                                apb_pready_nxt = 1'b1 ;
                                            end
                                        else
                                            begin
                                                apb_pready_nxt = 1'b1 ;
                                                apb_prdata_nxt = wb_dat_i ;
                                                //apb_pslverr_nxt = lmmi_error_i;
                                            end
                                    end// wb_ack_i
                            end// ST_BUS_REQ
                        ST_BUS_DAT : 
                            begin
                                if ((wb_ack_i & (~wb_we_o))) 
                                //else if(timeout_flag) begin
                                //  apb_pready_nxt  = 1'b1;
                                //  apb_prdata_nxt  = 32'd0;
                                //  //apb_pslverr_nxt = 1'b1;
                                //end // timeout_flag
                                    begin
                                        apb_pready_nxt = 1'b1 ;
                                        apb_prdata_nxt = wb_dat_i ;
                                        //apb_pslverr_nxt  = lmmi_error_i;
                                    end// wb_ack_i & (~wb_we_o)
                            end// ST_BUS_DAT
                        ST_BUS_WAIT : 
                            begin
                                apb_pready_nxt = 1'b0 ;
                                //req_timer_nxt      = 8'd0;
                                //timeout_flag_nxt   = 1'b0;
                            end// ST_BUS_WAIT
                        default : 
                            begin
                                apb_pready_nxt = 1'b0 ;
                                //req_timer_nxt      = 8'd0;
                                //timeout_flag_nxt   = 1'b0;
                                if (apb_psel_i) 
                                    begin
                                        wb_cyc_nxt = 1'b1 ;
                                        wb_stb_nxt = 1'b1 ;
                                        wb_we_nxt = apb_pwrite_i ;
                                        wb_adr_nxt = apb_paddr_i ;
                                        wb_dat_nxt = apb_pwdata_i ;
                                    end
                                else
                                    begin
                                        wb_cyc_nxt = 1'b0 ;
                                        wb_stb_nxt = 1'b0 ;
                                        wb_we_nxt = 1'b0 ;
                                    end
                            end// ST_BUS_IDLE
                        endcase 
                    end//--always @*--
                //--------------------------------------------
                //-- Sequential block --
                //--------------------------------------------
                always
                    @(posedge clk_i or 
                        posedge rst_i)
                    begin
                        if (rst_i) 
                            begin
                                bus_sm_cs <=  ST_BUS_IDLE ;
                                /*AUTORESET*/
                                // Beginning of autoreset for uninitialized flops
                                apb_prdata_o <=  {DATA_WIDTH{1'b0}} ;
                                apb_pready_o <=  1'h0 ;
                                //apb_pslverr_o <= 1'h0;
                                wb_adr_o <=  {ADDR_WIDTH{1'b0}} ;
                                wb_cyc_o <=  1'h0 ;
                                wb_stb_o <=  1'h0 ;
                                wb_dat_o <=  {DATA_WIDTH{1'b0}} ;
                                wb_we_o <=  1'h0 ;
                                // End of automatics
                            end
                        else
                            begin
                                bus_sm_cs <=  bus_sm_ns ;
                                wb_cyc_o <=  wb_cyc_nxt ;
                                wb_stb_o <=  wb_stb_nxt ;
                                wb_we_o <=  wb_we_nxt ;
                                wb_adr_o <=  wb_adr_nxt ;
                                wb_dat_o <=  wb_dat_nxt ;
                                apb_pready_o <=  apb_pready_nxt ;
                                //apb_pslverr_o <= apb_pslverr_nxt ;
                                apb_prdata_o <=  apb_prdata_nxt ;
                            end
                    end//--always @(posedge clk_i or posedge rst_i)--
            end
        else
            begin : genblk1
                // REG_OUTPUT == 0
                reg wb_busy_nxt ; 
                reg wb_busy ; 
                reg prev_req_granted ; 
                reg [(DATA_WIDTH - 1):0] reg_apb_prdata ; 
                reg reg_wb_cyc ; 
                reg reg_wb_stb ; 
                reg reg_wb_we ; 
                reg [(ADDR_WIDTH - 1):0] reg_wb_adr ; 
                reg [(DATA_WIDTH - 1):0] reg_wb_dat ; 
                //--------------------------------------------
                //-- WB request --
                //--------------------------------------------
                always
                    @(*)
                    begin
                        if (wb_busy) 
                            begin
                                wb_cyc_o = reg_wb_cyc ;
                                wb_stb_o = reg_wb_stb ;
                                wb_we_o = reg_wb_we ;
                                wb_adr_o = reg_wb_adr ;
                                wb_dat_o = reg_wb_dat ;
                            end
                        else
                            begin
                                wb_cyc_o = apb_psel_i ;
                                wb_stb_o = apb_psel_i ;
                                wb_we_o = apb_pwrite_i ;
                                wb_adr_o = apb_paddr_i ;
                                wb_dat_o = apb_pwdata_i ;
                            end
                    end//--always @*--
                //--------------------------------------------
                //-- APB outputs --
                //--------------------------------------------
                always
                    @(*)
                    begin
                        if (wb_busy) 
                            begin
                                apb_pready_o = ((prev_req_granted | (wb_ack_i & wb_we_o)) | (wb_ack_i & (~wb_we_o))) ;//|
                                //timeout_flag;
                                apb_prdata_o = ((wb_ack_i & (~wb_we_o)) ? wb_dat_i : reg_apb_prdata) ;
                                //apb_pslverr_o = (lmmi_rdata_valid_i)? lmmi_error_i : timeout_flag;
                            end
                        else
                            begin
                                apb_pready_o = 1'b0 ;
                                apb_prdata_o = reg_apb_prdata ;
                                //apb_pslverr_o = 1'b0;
                            end
                    end//--always @*--
                //--------------------------------------------
                //-- WB busy --
                //--------------------------------------------
                always
                    @(*)
                    begin
                        wb_busy_nxt = ((wb_busy & (~(apb_penable_i & apb_pready_o))) | ((~wb_busy) & apb_psel_i)) ;
                    end//--always @*--
                //--------------------------------------------
                //-- Request timer --
                //--------------------------------------------
                //always @* begin
                //  if(wb_busy) begin
                //    req_timer_nxt    = req_timer + {7'd0, ~timeout_flag};
                //    timeout_flag_nxt = &req_timer[7:1];
                //  end
                //  else begin
                //    req_timer_nxt    = 8'd0;
                //    timeout_flag_nxt = 1'b0;
                //  end
                //end //--always @*--
                //--------------------------------------------
                //-- Sequential block --
                //--------------------------------------------
                always
                    @(posedge clk_i or 
                        posedge rst_i)
                    begin
                        if (rst_i) 
                            begin
                                /*AUTORESET*/
                                // Beginning of autoreset for uninitialized flops
                                wb_busy <=  1'h0 ;
                                prev_req_granted <=  1'h0 ;
                                reg_apb_prdata <=  {DATA_WIDTH{1'b0}} ;
                                reg_wb_adr = {ADDR_WIDTH{1'b0}} ;
                                reg_wb_cyc = 1'h0 ;
                                reg_wb_stb = 1'h0 ;
                                reg_wb_dat = {DATA_WIDTH{1'b0}} ;
                                reg_wb_we = 1'h0 ;
                                // End of automatics
                            end
                        else
                            begin
                                prev_req_granted <=  ((wb_cyc_o & wb_stb_o) & wb_ack_i) ;
                                reg_apb_prdata <=  apb_prdata_o ;
                                wb_busy <=  wb_busy_nxt ;
                                reg_wb_cyc = ((wb_cyc_o & wb_stb_o) & (~wb_ack_i)) ;
                                reg_wb_stb = ((wb_cyc_o & wb_stb_o) & (~wb_ack_i)) ;
                                reg_wb_we = (((wb_we_o & wb_cyc_o) & wb_stb_o) & (~wb_ack_i)) ;
                                reg_wb_adr = wb_adr_o ;
                                reg_wb_dat = wb_dat_o ;
                            end
                    end//--always @(posedge clk_i or posedge rst_i)--
            end
    endgenerate

//--------------------------------------------
//-- Sequential block --
//--------------------------------------------
//always @(posedge clk_i or posedge rst_i) begin
//  if(rst_i) begin
//    /*AUTORESET*/
//    // Beginning of autoreset for uninitialized flops
//    req_timer <= 8'h0;
//    timeout_flag <= 1'h0;
//    // End of automatics
//  end
//  else begin
//    req_timer <= req_timer_nxt;
//    timeout_flag <= timeout_flag_nxt;
//  end
//end //--always @(posedge clk_i or posedge rst_i)--
//`ifdef SIMULATION
//always @(posedge timeout_flag) begin
//  $display("[%t][%m] Warning : APB access @addr=%0h has timed out!",$time,apb_paddr_i);
//end //--always @*--
//`endif
//--------------------------------------------------------------------------
//--- Module Instantiation ---
//--------------------------------------------------------------------------
//--apb2wb--
endmodule



`timescale 1ns/1ps
// =============================================================================
// >>>>>>>>>>>>>>>>>>>>>>>>> COPYRIGHT NOTICE <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
// -----------------------------------------------------------------------------
//   Copyright (c) 2025 by Lattice Semiconductor Corporation
//   ALL RIGHTS RESERVED
// -----------------------------------------------------------------------------
//
//   Permission:
//
//      Lattice SG Pte. Ltd. grants permission to use this code
//      pursuant to the terms of the Lattice Reference Design License Agreement.
//
//
//   Disclaimer:
//
//      This VHDL or Verilog source code is intended as a design reference
//      which illustrates how these types of functions can be implemented.
//      It is the user's responsibility to verify their design for
//      consistency and functionality through the use of formal
//      verification methods.  Lattice provides no warranty
//      regarding the use or functionality of this code.
//
// -----------------------------------------------------------------------------
//
//                  Lattice SG Pte. Ltd.
//                  101 Thomson Road, United Square #07-02
//                  Singapore 307591
//
//
//                  TEL: 1-800-Lattice (USA and Canada)
//                       +65-6631-2000 (Singapore)
//                       +1-503-268-8001 (other locations)
//
//                  web: http://www.latticesemi.com/
//                  email: techsupport@latticesemi.com
//
// -----------------------------------------------------------------------------
//
// =============================================================================
//                         FILE DETAILS
// Project               :
// File                  : lscc_efb.v
// Title                 :
// Description           : EFB Module IP top
// =============================================================================
//                        REVISION HISTORY
// Version               : 1.0.0.
// Author(s)             :
// Mod. Date             :
// Changes Made          : Initial release.
// =============================================================================
module efb_flash_i2c_ipgen_lscc_efb #(parameter FAMILY = "LFMXO4", 
        parameter DEVICE = "LFMXO4-015HC", 
        parameter DEVICE_ID_TB = 19595331, 
        parameter EFB_WB_IN = 1, 
        parameter EFB_INTERFACE_IN = "WISHBONE", 
        parameter EFB_I2C1 = "DISABLED", 
        parameter EFB_I2C2 = "DISABLED", 
        parameter EFB_SPI = "DISABLED", 
        parameter EFB_TC = "DISABLED", 
        parameter EFB_TC_PORTMODE = "NO_WB", 
        parameter EFB_PLL_IN = 0, 
        parameter EFB_PLL_NUM_IN = 1, 
        parameter EFB_UFM = "DISABLED", 
        parameter EFB_WB_CLK_FREQ = "50.0", 
        parameter EFB_WB_CLK_FREQ_TB = 50.0, 
        parameter DEV_DENSITY = "015", 
        parameter UFM_INIT_PAGES = "0", 
        parameter UFM_INIT_START_PAGE = "0", 
        parameter UFM_INIT_ALL_ZEROS = "ENABLED", 
        parameter UFM_INIT_FILE_NAME = "NONE", 
        parameter UFM_INIT_FILE_FORMAT = "HEX", 
        parameter I2C1_ADDRESSING = "7BIT", 
        parameter I2C2_ADDRESSING = "7BIT", 
        parameter I2C1_SLAVE_ADDR = "0b1000001", 
        parameter I2C2_SLAVE_ADDR = "0b1000010", 
        parameter I2C1_BUS_PERF = "100kHz", 
        parameter I2C2_BUS_PERF = "100kHz", 
        parameter I2C1_CLK_DIVIDER = "125", 
        parameter I2C2_CLK_DIVIDER = "125", 
        parameter I2C1_GEN_CALL = "DISABLED", 
        parameter I2C2_GEN_CALL = "DISABLED", 
        parameter I2C1_WAKEUP = "DISABLED", 
        parameter I2C2_WAKEUP = "DISABLED", 
        parameter EFB_I2C1_CFG_TB = "I2C1_USER", 
        parameter SPI_MODE = "SLAVE", 
        parameter SPI_CLK_DIVIDER = "1", 
        parameter SPI_LSB_FIRST = "DISABLED", 
        parameter SPI_CLK_INV = "DISABLED", 
        parameter SPI_PHASE_ADJ = "DISABLED", 
        parameter SPI_SLAVE_HANDSHAKE = "DISABLED", 
        parameter SPI_INTR_TXRDY = "DISABLED", 
        parameter SPI_INTR_RXRDY = "DISABLED", 
        parameter SPI_INTR_TXOVR = "DISABLED", 
        parameter SPI_INTR_RXOVR = "DISABLED", 
        parameter SPI_WAKEUP = "DISABLED", 
        parameter SPI_CS_NUM = 1, 
        parameter TC_MODE = "CTCM", 
        parameter TC_SCLK_SEL = "PCLOCK", 
        parameter TC_CCLK_SEL = "1", 
        parameter GSR = "ENABLED", 
        parameter TC_TOP_SET = "65535", 
        parameter TC_OCR_SET = "32767", 
        parameter TC_OC_MODE = "TOGGLE", 
        parameter TC_RESETN = "ENABLED", 
        parameter TC_TOP_SEL = "ON", 
        parameter TC_OV_INT = "OFF", 
        parameter TC_OCR_INT = "OFF", 
        parameter TC_ICR_INT = "OFF", 
        parameter TC_OVERFLOW = "DISABLED", 
        parameter TC_ICAPTURE = "DISABLED") (
    // -----------------------------------------------------------------------------
    // Input/Output Ports
    // -----------------------------------------------------------------------------
    //----------------------------
    // WISHBONE Interface
    //----------------------------
    input wb_clk_i, 
    input wb_rst_i, 
    input wb_cyc_i, 
    input wb_stb_i, 
    input wb_we_i, 
    input [7:0] wb_adr_i, 
    input [7:0] wb_dat_i, 
    output [7:0] wb_dat_o, 
    output wb_ack_o, 
    //----------------------------
    // APB Interface
    //----------------------------
    input clk_i, 
    input rstn_i, 
    input apb_penable_i, 
    input apb_psel_i, 
    input apb_pwrite_i, 
    input [7:0] apb_paddr_i, 
    input [7:0] apb_pwdata_i, 
    output apb_pready_o, 
    output [7:0] apb_prdata_o, 
    output apb_pslverr_o, 
    //----------------------------
    // I2C Interface
    //----------------------------
    inout i2c1_scl, 
    inout i2c1_sda, 
    inout i2c2_scl, 
    inout i2c2_sda, 
    output i2c1_irqo, 
    output i2c2_irqo, 
    output cfg_wake, 
    output cfg_stdby, 
    //----------------------------
    // UFM
    //----------------------------
    input ufm_sn, 
    output wbc_ufm_irq, 
    //----------------------------
    // PLL
    //----------------------------
    input pll0_ack_i, 
    input [7:0] pll0_dati_i, 
    output pll0_clk_o, 
    output pll0_rst_o, 
    output [4:0] pll0_addr_o, 
    output [7:0] pll0_dato_o, 
    output pll0_we_o, 
    output pll0_stb_o, 
    input pll1_ack_i, 
    input [7:0] pll1_dati_i, 
    output pll1_clk_o, 
    output pll1_rst_o, 
    output [4:0] pll1_addr_o, 
    output [7:0] pll1_dato_o, 
    output pll1_we_o, 
    output pll1_stb_o, 
    //----------------------------
    // Timer / Counter
    //----------------------------
    input tc_clki, 
    input tc_rstn, 
    input tc_ic, 
    output tc_int, 
    output tc_oc, 
    inout spi_clk, 
    inout spi_miso, 
    inout spi_mosi, 
    input spi_scsn, 
    output [(SPI_CS_NUM - 1):0] spi_csn, 
    output spi_irq, 
    //----------------------------
    // Others
    //----------------------------
    output int_o) ;
    // -----------------------------------------------------------------------------
    // Wire Declarations
    // -----------------------------------------------------------------------------
    // WISHBONE / APB
    wire wb_clk_w ; 
    wire wb_rst_w ; 
    wire wb_cyc_w ; 
    wire wb_stb_w ; 
    wire wb_we_w ; 
    wire [7:0] wb_adr_w ; 
    wire [7:0] wb_idat_w ; 
    wire [7:0] wb_odat_w ; 
    wire wb_ack_w ; 
    // -----------------------------------------------------------------------------
    // Port Assignments
    // -----------------------------------------------------------------------------
    if ((EFB_INTERFACE_IN == "APB")) 
        begin : _APB_assign
            assign wb_clk_w = clk_i ; 
            assign wb_rst_w = (~rstn_i) ; 
            assign wb_dat_o = wb_odat_w ; 
            assign wb_ack_o = wb_ack_w ; 
            assign int_o = (((wbc_ufm_irq | i2c1_irqo) | i2c2_irqo) | spi_irq) ; 
            assign apb_pslverr_o = 1'b0 ; 
        end
    else
        begin : _WISHBONE_assign
            assign wb_clk_w = wb_clk_i ; 
            assign wb_rst_w = wb_rst_i ; 
            assign wb_cyc_w = wb_cyc_i ; 
            assign wb_stb_w = wb_stb_i ; 
            assign wb_we_w = wb_we_i ; 
            assign wb_adr_w = wb_adr_i ; 
            assign wb_idat_w = wb_dat_i ; 
            assign wb_dat_o = wb_odat_w ; 
            assign wb_ack_o = wb_ack_w ; 
            assign apb_pready_o = 1'b0 ; 
            assign apb_prdata_o = 8'd0 ; 
            assign apb_pslverr_o = 1'b0 ; 
            assign int_o = 1'b0 ; 
        end
    // -----------------------------------------------------------------------------
    // Submodules
    // -----------------------------------------------------------------------------
    if ((EFB_INTERFACE_IN == "APB")) 
        begin : _apb2wb
            efb_flash_i2c_ipgen_lscc_apb2wb #(.DATA_WIDTH(8),
                    .ADDR_WIDTH(8),
                    .REG_OUTPUT(1)) u_wishbone_bridge (.clk_i(clk_i), 
                        .rst_i((~rstn_i)), 
                        .apb_penable_i(apb_penable_i), 
                        .apb_psel_i(apb_psel_i), 
                        .apb_pwrite_i(apb_pwrite_i), 
                        .apb_paddr_i(apb_paddr_i), 
                        .apb_pwdata_i(apb_pwdata_i), 
                        .apb_pready_o(apb_pready_o), 
                        .apb_prdata_o(apb_prdata_o), 
                        .wb_ack_i(wb_ack_w), 
                        .wb_dat_i(wb_odat_w), 
                        .wb_cyc_o(wb_cyc_w), 
                        .wb_stb_o(wb_stb_w), 
                        .wb_we_o(wb_we_w), 
                        .wb_adr_o(wb_adr_w), 
                        .wb_dat_o(wb_idat_w)) ; 
        end
    if ((FAMILY == "LFMXO4")) 
        begin : _xo4_efb
            efb_flash_i2c_ipgen_lscc_xo4_efb #(.EFB_I2C1(EFB_I2C1),
                    .EFB_I2C2(EFB_I2C2),
                    .EFB_SPI(EFB_SPI),
                    .EFB_TC(EFB_TC),
                    .EFB_TC_PORTMODE(EFB_TC_PORTMODE),
                    .EFB_UFM(EFB_UFM),
                    .EFB_WB_CLK_FREQ(EFB_WB_CLK_FREQ),
                    .DEV_DENSITY(DEV_DENSITY),
                    .UFM_INIT_PAGES(UFM_INIT_PAGES),
                    .UFM_INIT_START_PAGE(UFM_INIT_START_PAGE),
                    .UFM_INIT_ALL_ZEROS(UFM_INIT_ALL_ZEROS),
                    .UFM_INIT_FILE_NAME(UFM_INIT_FILE_NAME),
                    .UFM_INIT_FILE_FORMAT(UFM_INIT_FILE_FORMAT),
                    .I2C1_ADDRESSING(I2C1_ADDRESSING),
                    .I2C2_ADDRESSING(I2C2_ADDRESSING),
                    .I2C1_SLAVE_ADDR(I2C1_SLAVE_ADDR),
                    .I2C2_SLAVE_ADDR(I2C2_SLAVE_ADDR),
                    .I2C1_BUS_PERF(I2C1_BUS_PERF),
                    .I2C2_BUS_PERF(I2C2_BUS_PERF),
                    .I2C1_CLK_DIVIDER(I2C1_CLK_DIVIDER),
                    .I2C2_CLK_DIVIDER(I2C2_CLK_DIVIDER),
                    .I2C1_GEN_CALL(I2C1_GEN_CALL),
                    .I2C2_GEN_CALL(I2C2_GEN_CALL),
                    .I2C1_WAKEUP(I2C1_WAKEUP),
                    .I2C2_WAKEUP(I2C2_WAKEUP),
                    .EFB_I2C1_CFG_TB(EFB_I2C1_CFG_TB),
                    .SPI_MODE(SPI_MODE),
                    .SPI_CLK_DIVIDER(SPI_CLK_DIVIDER),
                    .SPI_LSB_FIRST(SPI_LSB_FIRST),
                    .SPI_CLK_INV(SPI_CLK_INV),
                    .SPI_PHASE_ADJ(SPI_PHASE_ADJ),
                    .SPI_SLAVE_HANDSHAKE(SPI_SLAVE_HANDSHAKE),
                    .SPI_INTR_TXRDY(SPI_INTR_TXRDY),
                    .SPI_INTR_RXRDY(SPI_INTR_RXRDY),
                    .SPI_INTR_TXOVR(SPI_INTR_TXOVR),
                    .SPI_INTR_RXOVR(SPI_INTR_RXOVR),
                    .SPI_WAKEUP(SPI_WAKEUP),
                    .SPI_CS_NUM(SPI_CS_NUM),
                    .TC_MODE(TC_MODE),
                    .TC_SCLK_SEL(TC_SCLK_SEL),
                    .TC_CCLK_SEL(TC_CCLK_SEL),
                    .GSR(GSR),
                    .TC_TOP_SET(TC_TOP_SET),
                    .TC_OCR_SET(TC_OCR_SET),
                    .TC_OC_MODE(TC_OC_MODE),
                    .TC_RESETN(TC_RESETN),
                    .TC_TOP_SEL(TC_TOP_SEL),
                    .TC_OV_INT(TC_OV_INT),
                    .TC_OCR_INT(TC_OCR_INT),
                    .TC_ICR_INT(TC_ICR_INT),
                    .TC_OVERFLOW(TC_OVERFLOW),
                    .TC_ICAPTURE(TC_ICAPTURE)) u_efb_core (.wb_clk_i(wb_clk_w), 
                        .wb_rst_i(wb_rst_w), 
                        .wb_cyc_i(wb_cyc_w), 
                        .wb_stb_i(wb_stb_w), 
                        .wb_we_i(wb_we_w), 
                        .wb_adr_i(wb_adr_w), 
                        .wb_dat_i(wb_idat_w), 
                        .wb_dat_o(wb_odat_w), 
                        .wb_ack_o(wb_ack_w), 
                        .i2c1_irqo(i2c1_irqo), 
                        .i2c2_irqo(i2c2_irqo), 
                        .wbc_ufm_irq(wbc_ufm_irq), 
                        .cfg_wake(cfg_wake), 
                        .cfg_stdby(cfg_stdby), 
                        .pll0_ack_i(pll0_ack_i), 
                        .pll0_dati_i(pll0_dati_i), 
                        .pll0_clk_o(pll0_clk_o), 
                        .pll0_rst_o(pll0_rst_o), 
                        .pll0_addr_o(pll0_addr_o), 
                        .pll0_dato_o(pll0_dato_o), 
                        .pll0_we_o(pll0_we_o), 
                        .pll0_stb_o(pll0_stb_o), 
                        .pll1_ack_i(pll1_ack_i), 
                        .pll1_dati_i(pll1_dati_i), 
                        .pll1_clk_o(pll1_clk_o), 
                        .pll1_rst_o(pll1_rst_o), 
                        .pll1_addr_o(pll1_addr_o), 
                        .pll1_dato_o(pll1_dato_o), 
                        .pll1_we_o(pll1_we_o), 
                        .pll1_stb_o(pll1_stb_o), 
                        .tc_clki(tc_clki), 
                        .tc_rstn(tc_rstn), 
                        .tc_ic(tc_ic), 
                        .tc_int(tc_int), 
                        .tc_oc(tc_oc), 
                        .i2c1_scl(i2c1_scl), 
                        .i2c1_sda(i2c1_sda), 
                        .i2c2_scl(i2c2_scl), 
                        .i2c2_sda(i2c2_sda), 
                        .spi_clk(spi_clk), 
                        .spi_miso(spi_miso), 
                        .spi_mosi(spi_mosi), 
                        .spi_scsn(spi_scsn), 
                        .ufm_sn(ufm_sn), 
                        .spi_csn(spi_csn), 
                        .spi_irq(spi_irq)) ; 
        end
endmodule



`timescale 1ns/1ps
// =============================================================================
// >>>>>>>>>>>>>>>>>>>>>>>>> COPYRIGHT NOTICE <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
// -----------------------------------------------------------------------------
//   Copyright (c) 2025 by Lattice Semiconductor Corporation
//   ALL RIGHTS RESERVED
// -----------------------------------------------------------------------------
//
//   Permission:
//
//      Lattice SG Pte. Ltd. grants permission to use this code
//      pursuant to the terms of the Lattice Reference Design License Agreement.
//
//
//   Disclaimer:
//
//      This VHDL or Verilog source code is intended as a design reference
//      which illustrates how these types of functions can be implemented.
//      It is the user's responsibility to verify their design for
//      consistency and functionality through the use of formal
//      verification methods.  Lattice provides no warranty
//      regarding the use or functionality of this code.
//
// -----------------------------------------------------------------------------
//
//                  Lattice SG Pte. Ltd.
//                  101 Thomson Road, United Square #07-02
//                  Singapore 307591
//
//
//                  TEL: 1-800-Lattice (USA and Canada)
//                       +65-6631-2000 (Singapore)
//                       +1-503-268-8001 (other locations)
//
//                  web: http://www.latticesemi.com/
//                  email: techsupport@latticesemi.com
//
// -----------------------------------------------------------------------------
//
// =============================================================================
//                         FILE DETAILS
// Project               :
// File                  : lscc_xo4_efb.v
// Title                 :
// Description           : Core module for EFB instance using LFMXO4
// =============================================================================
//                        REVISION HISTORY
// Version               : 1.0.0.
// Author(s)             :
// Mod. Date             :
// Changes Made          : Initial release.
// =============================================================================
module efb_flash_i2c_ipgen_lscc_xo4_efb #(parameter EFB_I2C1 = "DISABLED", 
        parameter EFB_I2C2 = "DISABLED", 
        parameter EFB_SPI = "DISABLED", 
        parameter EFB_TC = "DISABLED", 
        parameter EFB_TC_PORTMODE = "NO_WB", 
        parameter EFB_UFM = "DISABLED", 
        parameter EFB_WB_CLK_FREQ = "50.0", 
        parameter DEV_DENSITY = "015", 
        parameter UFM_INIT_PAGES = "0", 
        parameter UFM_INIT_START_PAGE = "0", 
        parameter UFM_INIT_ALL_ZEROS = "ENABLED", 
        parameter UFM_INIT_FILE_NAME = "NONE", 
        parameter UFM_INIT_FILE_FORMAT = "HEX", 
        parameter I2C1_ADDRESSING = "7BIT", 
        parameter I2C2_ADDRESSING = "7BIT", 
        parameter I2C1_SLAVE_ADDR = "0b1000001", 
        parameter I2C2_SLAVE_ADDR = "0b1000010", 
        parameter I2C1_BUS_PERF = "100kHz", 
        parameter I2C2_BUS_PERF = "100kHz", 
        parameter I2C1_CLK_DIVIDER = "125", 
        parameter I2C2_CLK_DIVIDER = "125", 
        parameter I2C1_GEN_CALL = "DISABLED", 
        parameter I2C2_GEN_CALL = "DISABLED", 
        parameter I2C1_WAKEUP = "DISABLED", 
        parameter I2C2_WAKEUP = "DISABLED", 
        parameter EFB_I2C1_CFG_TB = "I2C1_USER", 
        parameter SPI_MODE = "SLAVE", 
        parameter SPI_CLK_DIVIDER = "1", 
        parameter SPI_LSB_FIRST = "DISABLED", 
        parameter SPI_CLK_INV = "DISABLED", 
        parameter SPI_PHASE_ADJ = "DISABLED", 
        parameter SPI_SLAVE_HANDSHAKE = "DISABLED", 
        parameter SPI_INTR_TXRDY = "DISABLED", 
        parameter SPI_INTR_RXRDY = "DISABLED", 
        parameter SPI_INTR_TXOVR = "DISABLED", 
        parameter SPI_INTR_RXOVR = "DISABLED", 
        parameter SPI_WAKEUP = "DISABLED", 
        parameter SPI_CS_NUM = 1, 
        parameter TC_MODE = "CTCM", 
        parameter TC_SCLK_SEL = "PCLOCK", 
        parameter TC_CCLK_SEL = "1", 
        parameter GSR = "ENABLED", 
        parameter TC_TOP_SET = "65535", 
        parameter TC_OCR_SET = "32767", 
        parameter TC_OC_MODE = "TOGGLE", 
        parameter TC_RESETN = "ENABLED", 
        parameter TC_TOP_SEL = "ON", 
        parameter TC_OV_INT = "OFF", 
        parameter TC_OCR_INT = "OFF", 
        parameter TC_ICR_INT = "OFF", 
        parameter TC_OVERFLOW = "DISABLED", 
        parameter TC_ICAPTURE = "DISABLED") (
    // -----------------------------------------------------------------------------
    // Input/Output Ports
    // -----------------------------------------------------------------------------
    //----------------------------
    // WISHBONE Interface
    //----------------------------
    input wb_clk_i, 
    input wb_rst_i, 
    input wb_cyc_i, 
    input wb_stb_i, 
    input wb_we_i, 
    input [7:0] wb_adr_i, 
    input [7:0] wb_dat_i, 
    output [7:0] wb_dat_o, 
    output wb_ack_o, 
    //----------------------------
    // I2C Interface
    //----------------------------
    inout i2c1_scl, 
    inout i2c1_sda, 
    inout i2c2_scl, 
    inout i2c2_sda, 
    output i2c1_irqo, 
    output i2c2_irqo, 
    output cfg_wake, 
    output cfg_stdby, 
    //----------------------------
    // UFM
    //----------------------------
    output wbc_ufm_irq, 
    //----------------------------
    // PLL
    //----------------------------
    input pll0_ack_i, 
    input [7:0] pll0_dati_i, 
    output pll0_clk_o, 
    output pll0_rst_o, 
    output [4:0] pll0_addr_o, 
    output [7:0] pll0_dato_o, 
    output pll0_we_o, 
    output pll0_stb_o, 
    input pll1_ack_i, 
    input [7:0] pll1_dati_i, 
    output pll1_clk_o, 
    output pll1_rst_o, 
    output [4:0] pll1_addr_o, 
    output [7:0] pll1_dato_o, 
    output pll1_we_o, 
    output pll1_stb_o, 
    //----------------------------
    // Timer/Counter
    //----------------------------
    input tc_clki, 
    input tc_rstn, 
    input tc_ic, 
    output tc_int, 
    output tc_oc, 
    //----------------------------
    // SPI
    //----------------------------
    inout spi_clk, 
    inout spi_miso, 
    inout spi_mosi, 
    input spi_scsn, 
    input ufm_sn, 
    output [(SPI_CS_NUM - 1):0] spi_csn, 
    output spi_irq) ;
    // -----------------------------------------------------------------------------
    // Wire Declarations
    // -----------------------------------------------------------------------------
    // PLL
    wire pll_clk_w ; 
    wire pll_rst_w ; 
    wire pll_weo_w ; 
    wire [4:0] pll_addr_w ; 
    wire [7:0] pll_dato_w ; 
    assign pll0_clk_o = pll_clk_w ; 
    assign pll1_clk_o = pll_clk_w ; 
    assign pll0_rst_o = pll_rst_w ; 
    assign pll1_rst_o = pll_rst_w ; 
    assign pll0_we_o = pll_weo_w ; 
    assign pll1_we_o = pll_weo_w ; 
    assign pll0_addr_o = pll_addr_w ; 
    assign pll1_addr_o = pll_addr_w ; 
    assign pll0_dato_o = pll_dato_w ; 
    assign pll1_dato_o = pll_dato_w ; 
    // Primary I2C
    wire scl_in_1_w ; 
    wire sda_in_1_w ; 
    wire scl_out_en_1_w ; 
    wire sda_out_en_1_w ; 
    wire scl_out_1_w ; 
    wire sda_out_1_w ; 
    // Secondary I2C
    wire scl_in_2_w ; 
    wire sda_in_2_w ; 
    wire scl_out_en_2_w ; 
    wire sda_out_en_2_w ; 
    wire scl_out_2_w ; 
    wire sda_out_2_w ; 
    // SPI
    wire [7:0] spi_csn_w ; 
    wire mosi_in_w ; 
    wire miso_in_w ; 
    wire sclk_in_w ; 
    wire mosi_out_en_w ; 
    wire miso_out_en_w ; 
    wire sclk_out_en_w ; 
    wire mosi_out_w ; 
    wire miso_out_w ; 
    wire sclk_out_w ; 
    // -----------------------------------------------------------------------------
    // Bi-directional (Tri-state) Buffers
    // -----------------------------------------------------------------------------
    BB BB_scl_1 (.I(scl_out_1_w), 
                .T(scl_out_en_1_w), 
                .B(i2c1_scl), 
                .O(scl_in_1_w)) ; 
    BB BB_sda_1 (.I(sda_out_1_w), 
                .T(sda_out_en_1_w), 
                .B(i2c1_sda), 
                .O(sda_in_1_w)) ; 
    BB BB_scl_2 (.I(scl_out_2_w), 
                .T(scl_out_en_2_w), 
                .B(i2c2_scl), 
                .O(scl_in_2_w)) ; 
    BB BB_sda_2 (.I(sda_out_2_w), 
                .T(sda_out_en_2_w), 
                .B(i2c2_sda), 
                .O(sda_in_2_w)) ; 
    BB BB_mosi (.I(mosi_out_w), 
                .T(mosi_out_en_w), 
                .B(spi_mosi), 
                .O(mosi_in_w)) ; 
    BB BB_miso (.I(miso_out_w), 
                .T(miso_out_en_w), 
                .B(spi_miso), 
                .O(miso_in_w)) ; 
    BB BB_clk (.I(sclk_out_w), 
                .T(sclk_out_en_w), 
                .B(spi_clk), 
                .O(sclk_in_w)) ; 
    assign spi_csn[(SPI_CS_NUM - 1):0] = spi_csn_w[(SPI_CS_NUM - 1):0] ; 
    // -----------------------------------------------------------------------------
    // EFB instance
    // -----------------------------------------------------------------------------
    EFB #(.EFB_I2C1(EFB_I2C1),
            .EFB_I2C2(EFB_I2C2),
            .EFB_SPI(EFB_SPI),
            .EFB_TC(EFB_TC),
            .EFB_TC_PORTMODE(EFB_TC_PORTMODE),
            .EFB_UFM(EFB_UFM),
            .EFB_WB_CLK_FREQ(EFB_WB_CLK_FREQ),
            .DEV_DENSITY(DEV_DENSITY),
            .UFM_INIT_PAGES(UFM_INIT_PAGES),
            .UFM_INIT_START_PAGE(UFM_INIT_START_PAGE),
            .UFM_INIT_ALL_ZEROS(UFM_INIT_ALL_ZEROS),
            .UFM_INIT_FILE_NAME(UFM_INIT_FILE_NAME),
            .UFM_INIT_FILE_FORMAT(UFM_INIT_FILE_FORMAT),
            .I2C1_ADDRESSING(I2C1_ADDRESSING),
            .I2C2_ADDRESSING(I2C2_ADDRESSING),
            .I2C1_SLAVE_ADDR(I2C1_SLAVE_ADDR),
            .I2C2_SLAVE_ADDR(I2C2_SLAVE_ADDR),
            .I2C1_BUS_PERF(I2C1_BUS_PERF),
            .I2C2_BUS_PERF(I2C2_BUS_PERF),
            .I2C1_CLK_DIVIDER(I2C1_CLK_DIVIDER),
            .I2C2_CLK_DIVIDER(I2C2_CLK_DIVIDER),
            .I2C1_GEN_CALL(I2C1_GEN_CALL),
            .I2C2_GEN_CALL(I2C2_GEN_CALL),
            .I2C1_WAKEUP(I2C1_WAKEUP),
            .I2C2_WAKEUP(I2C2_WAKEUP),
            .SPI_MODE(SPI_MODE),
            .SPI_CLK_DIVIDER(SPI_CLK_DIVIDER),
            .SPI_LSB_FIRST(SPI_LSB_FIRST),
            .SPI_CLK_INV(SPI_CLK_INV),
            .SPI_PHASE_ADJ(SPI_PHASE_ADJ),
            .SPI_SLAVE_HANDSHAKE(SPI_SLAVE_HANDSHAKE),
            .SPI_INTR_TXRDY(SPI_INTR_TXRDY),
            .SPI_INTR_RXRDY(SPI_INTR_RXRDY),
            .SPI_INTR_TXOVR(SPI_INTR_TXOVR),
            .SPI_INTR_RXOVR(SPI_INTR_RXOVR),
            .SPI_WAKEUP(SPI_WAKEUP),
            .TC_MODE(TC_MODE),
            .TC_SCLK_SEL(TC_SCLK_SEL),
            .TC_CCLK_SEL(TC_CCLK_SEL),
            .GSR(GSR),
            .TC_TOP_SET(TC_TOP_SET),
            .TC_OCR_SET(TC_OCR_SET),
            .TC_OC_MODE(TC_OC_MODE),
            .TC_RESETN(TC_RESETN),
            .TC_TOP_SEL(TC_TOP_SEL),
            .TC_OV_INT(TC_OV_INT),
            .TC_OCR_INT(TC_OCR_INT),
            .TC_ICR_INT(TC_ICR_INT),
            .TC_OVERFLOW(TC_OVERFLOW),
            .TC_ICAPTURE(TC_ICAPTURE)) efb_0 (.WBCLKI(wb_clk_i),  // I
            .WBRSTI(wb_rst_i),  // I
            .WBCYCI(wb_cyc_i),  // I
            .WBSTBI(wb_stb_i),  // I
            .WBWEI(wb_we_i),  // I
            .WBADRI7(wb_adr_i[7]),  // I
            .WBADRI6(wb_adr_i[6]),  // I
            .WBADRI5(wb_adr_i[5]),  // I
            .WBADRI4(wb_adr_i[4]),  // I
            .WBADRI3(wb_adr_i[3]),  // I
            .WBADRI2(wb_adr_i[2]),  // I
            .WBADRI1(wb_adr_i[1]),  // I
            .WBADRI0(wb_adr_i[0]),  // I
            .WBDATI7(wb_dat_i[7]),  // I
            .WBDATI6(wb_dat_i[6]),  // I
            .WBDATI5(wb_dat_i[5]),  // I
            .WBDATI4(wb_dat_i[4]),  // I
            .WBDATI3(wb_dat_i[3]),  // I
            .WBDATI2(wb_dat_i[2]),  // I
            .WBDATI1(wb_dat_i[1]),  // I
            .WBDATI0(wb_dat_i[0]),  // I
            .PLL0DATI7(pll0_dati_i[7]),  // I
            .PLL0DATI6(pll0_dati_i[6]),  // I
            .PLL0DATI5(pll0_dati_i[5]),  // I
            .PLL0DATI4(pll0_dati_i[4]),  // I
            .PLL0DATI3(pll0_dati_i[3]),  // I
            .PLL0DATI2(pll0_dati_i[2]),  // I
            .PLL0DATI1(pll0_dati_i[1]),  // I
            .PLL0DATI0(pll0_dati_i[0]),  // I
            .PLL0ACKI(pll0_ack_i),  // I
            .PLL1DATI7(pll1_dati_i[7]),  // I
            .PLL1DATI6(pll1_dati_i[6]),  // I
            .PLL1DATI5(pll1_dati_i[5]),  // I
            .PLL1DATI4(pll1_dati_i[4]),  // I
            .PLL1DATI3(pll1_dati_i[3]),  // I
            .PLL1DATI2(pll1_dati_i[2]),  // I
            .PLL1DATI1(pll1_dati_i[1]),  // I
            .PLL1DATI0(pll1_dati_i[0]),  // I
            .PLL1ACKI(pll1_ack_i),  // I
            .I2C1SCLI(scl_in_1_w),  // I
            .I2C1SDAI(sda_in_1_w),  // I
            .I2C2SCLI(scl_in_2_w),  // I
            .I2C2SDAI(sda_in_2_w),  // I
            .SPISCKI(sclk_in_w),  // I
            .SPIMISOI(miso_in_w),  // I
            .SPIMOSII(mosi_in_w),  // I
            .SPISCSN(spi_scsn),  // I
            .TCCLKI(tc_clki),  // I
            .TCRSTN(tc_rstn),  // I
            .TCIC(tc_ic),  // I
            .UFMSN(ufm_sn),  // I
            .WBDATO7(wb_dat_o[7]),  // O
            .WBDATO6(wb_dat_o[6]),  // O
            .WBDATO5(wb_dat_o[5]),  // O
            .WBDATO4(wb_dat_o[4]),  // O
            .WBDATO3(wb_dat_o[3]),  // O
            .WBDATO2(wb_dat_o[2]),  // O
            .WBDATO1(wb_dat_o[1]),  // O
            .WBDATO0(wb_dat_o[0]),  // O
            .WBACKO(wb_ack_o),  // O
            .PLLCLKO(pll_clk_w),  // O
            .PLLRSTO(pll_rst_w),  // O
            .PLL0STBO(pll0_stb_o),  // O 
            .PLL1STBO(pll1_stb_o),  // O
            .PLLWEO(pll_weo_w),  // O
            .PLLADRO4(pll_addr_w[4]),  // O
            .PLLADRO3(pll_addr_w[3]),  // O
            .PLLADRO2(pll_addr_w[2]),  // O
            .PLLADRO1(pll_addr_w[1]),  // O
            .PLLADRO0(pll_addr_w[0]),  // O
            .PLLDATO7(pll_dato_w[7]),  // O
            .PLLDATO6(pll_dato_w[6]),  // O
            .PLLDATO5(pll_dato_w[5]),  // O
            .PLLDATO4(pll_dato_w[4]),  // O
            .PLLDATO3(pll_dato_w[3]),  // O
            .PLLDATO2(pll_dato_w[2]),  // O
            .PLLDATO1(pll_dato_w[1]),  // O
            .PLLDATO0(pll_dato_w[0]),  // O
            .I2C1SCLO(scl_out_1_w),  // O
            .I2C1SCLOEN(scl_out_en_1_w),  // O
            .I2C1SDAO(sda_out_1_w),  // O
            .I2C1SDAOEN(sda_out_en_1_w),  // O
            .I2C2SCLO(scl_out_2_w),  // O
            .I2C2SCLOEN(scl_out_en_2_w),  // O
            .I2C2SDAO(sda_out_2_w),  // O
            .I2C2SDAOEN(sda_out_en_2_w),  // O
            .I2C1IRQO(i2c1_irqo),  // O
            .I2C2IRQO(i2c2_irqo),  // O
            .SPISCKO(sclk_out_w),  // O
            .SPISCKEN(sclk_out_en_w),  // O
            .SPIMISOO(miso_out_w),  // O
            .SPIMISOEN(miso_out_en_w),  // O
            .SPIMOSIO(mosi_out_w),  // O
            .SPIMOSIEN(mosi_out_en_w),  // O
            .SPIMCSN0(spi_csn_w[0]),  // O
            .SPIMCSN1(spi_csn_w[1]),  // O
            .SPIMCSN2(spi_csn_w[2]),  // O
            .SPIMCSN3(spi_csn_w[3]),  // O
            .SPIMCSN4(spi_csn_w[4]),  // O
            .SPIMCSN5(spi_csn_w[5]),  // O
            .SPIMCSN6(spi_csn_w[6]),  // O
            .SPIMCSN7(spi_csn_w[7]),  // O
            .SPICSNEN(),  // O
            .SPIIRQO(spi_irq),  // O
            .TCINT(tc_int),  // O
            .TCOC(tc_oc),  // O
            .WBCUFMIRQ(wbc_ufm_irq),  // O
            .CFGWAKE(cfg_wake),  // O
            .CFGSTDBY(cfg_stdby) // O
            ) ; 
endmodule


