//   ==================================================================
//   >>>>>>>>>>>>>>>>>>>>>>> COPYRIGHT NOTICE <<<<<<<<<<<<<<<<<<<<<<<<<
//   ------------------------------------------------------------------
//   Copyright (c) 2006-2011 by Lattice Semiconductor Corporation
//   ------------------------------------------------------------------
//   ALL RIGHTS RESERVED
//
//   IMPORTANT: THIS FILE IS AUTO-GENERATED BY THE LATTICEMICO SYSTEM.
//
//   Permission:
//
//      Lattice Semiconductor grants permission to use this code
//      pursuant to the terms of the Lattice Semiconductor Corporation
//      Open Source License Agreement.
//
//   Disclaimer:
//
//      Lattice Semiconductor provides no warranty regarding the use or
//      functionality of this code. It is the user's responsibility to
//      verify the user’s design for consistency and functionality through
//      the use of formal verification methods.
//
//   --------------------------------------------------------------------
//
//                  Lattice Semiconductor Corporation
//                  5555 NE Moore Court
//                  Hillsboro, OR 97214
//                  U.S.A
//
//                  TEL: 1-800-Lattice (USA and Canada)
//                         503-286-8001 (other locations)
//
//                  web: http://www.latticesemi.com/
//                  email: techsupport@latticesemi.com
//
//   --------------------------------------------------------------------
//
//      Project:           lm32_xo2
//      File:              lm32_xo2_inst.v
//      Date:              Mi, 17 Jan 2024 05:45:07 MEZ
//      Version:           2.1
//      Targeted Family:   MachXO3D
//
//   =======================================================================

// Attn : This file is used for VHDL Wrapper

lm32_xo2_vhd lm32_xo2_u ( 
.clk_i(clk_i),
.reset_n(reset_n)
, .slave_passthruclk(slave_passthruclk) // 
, .slave_passthrurst(slave_passthrurst) // 
, .slave_passthruslv_adr(slave_passthruslv_adr) // [32-1:0]
, .slave_passthruslv_master_data(slave_passthruslv_master_data) // [32-1:0]
, .slave_passthruslv_slave_data(slave_passthruslv_slave_data) // [32-1:0]
, .slave_passthruslv_strb(slave_passthruslv_strb) // 
, .slave_passthruslv_cyc(slave_passthruslv_cyc) // 
, .slave_passthruslv_ack(slave_passthruslv_ack) // 
, .slave_passthruslv_err(slave_passthruslv_err) // 
, .slave_passthruslv_rty(slave_passthruslv_rty) // 
, .slave_passthruslv_sel(slave_passthruslv_sel) // [3:0] 
, .slave_passthruslv_we(slave_passthruslv_we) // 
, .slave_passthruslv_bte(slave_passthruslv_bte) // [1:0] 
, .slave_passthruslv_cti(slave_passthruslv_cti) // [2:0] 
, .slave_passthruslv_lock(slave_passthruslv_lock) // 
, .slave_passthruintr_active_high(slave_passthruintr_active_high) // 
, .master_passthrumstr_adr(master_passthrumstr_adr) // [32-1:0]
, .master_passthrumstr_data_to_slv(master_passthrumstr_data_to_slv) // [32-1:0]
, .master_passthrumstr_we(master_passthrumstr_we) // 
, .master_passthrumstr_stb(master_passthrumstr_stb) // 
, .master_passthrumstr_cyc(master_passthrumstr_cyc) // 
, .master_passthrumstr_lock(master_passthrumstr_lock) // 
, .master_passthrumstr_cti(master_passthrumstr_cti) // [2:0] 
, .master_passthrumstr_sel(master_passthrumstr_sel) // [4-1:0]
, .master_passthrumstr_bte(master_passthrumstr_bte) // [1:0] 
, .master_passthruclk(master_passthruclk) // 
, .master_passthrurst(master_passthrurst) // 
, .master_passthrumstr_data_from_slv(master_passthrumstr_data_from_slv) // [32-1:0]
, .master_passthrumstr_ack_from_slv(master_passthrumstr_ack_from_slv) // 
, .master_passthrumstr_rty_from_slv(master_passthrumstr_rty_from_slv) // 
, .master_passthrumstr_err_from_slv(master_passthrumstr_err_from_slv) // 
);
