// $Id: design_functions.c 1208 2026-08-08 16:11:40Z  $:

// generated by Lattice Mico tool
#include "system_conf.h"
// defines for our own design
#include "design_functions.h"
//
// Our definitions of the integer types like int8_t, uint8_t etc.
// correspond to stdint.h (not found here)
#include "my_types.h"


// set the properties of the software LEDs
// LED register: two bits / LED, 0 - off, 1..3 - predefined colours
// LED_BLINK register: one bit/LED, 1 - blink, 0 - don't blink
// in this design we have 4 LEDs
void set_led(uint32_t a, uint32_t blink)
{
    IO_WRITE(ADDR_LED, a);
    IO_WRITE(ADDR_LED_BLINK, blink);
    return;
}

// store the data & time defined in the automatically updated header file to the shared memory
void fill_date_time(void)
{
    IO_WRITE(COMP_DATE, (DTYear << 16) | (DTMonth  << 8) | DTDay);
    IO_WRITE(COMP_TIME, (DThour << 16) | (DTminute << 8) | DTsecond);
    return;
}

// Timer in FPGA design running at the system clock (same as CPU clock)
//  - send a command (see the .h file for details)
void timer_cmd(uint32_t tmr_cmd)
{
    IO_WRITE(CNF_TIMER, tmr_cmd);
    return;
}
// - read the timer, 0 is the current (eventually running)
//   1..3 are the 3 latches 0..2 (see the header file)
uint32_t timer_rd(uint32_t ch)
{
    return IO_READ(CNF_TIMER+4*(ch & 3) );
}

// start the CRC check of the FPGA configuration
void start_fpga_crc_check()
{
    IO_WRITE(ADDR_CONFIG_CHIP_CRC, (1 << BIT_CHIP_CRC_ENA) | (1 << BIT_CHIP_CRC_START) );
    return;
}

// get the FPGA CRC check result bytes
uint32_t get_fpga_crc_check()
{
    return IO_READ( ADDR_CONFIG_CHIP_CRC );
}

// I2C functions:

// start an i2c write, 1 to 4 bytes
void i2c_start_write(uint32_t slv_addr, int nwbytes, uint32_t wdata)
{
    uint32_t base_a;

    base_a = I2C_BASE_ADDRESS;

    // write 1..4 bytes to be sent to the output buffer as 32-bit word.
    // depending on the number of bytes to be sent:
    // n bytes     first byte to be sent        second byte     third byte      fourth byte
    //    4             31..24                  23..16          15..8           7..0
    //    3             23..16                  15..8           7..0
    //    2             15..8                   7..0
    //    1              7..0
    IO_WRITE(base_a | I2C_OFFS_WDAT, wdata);

    // the parameter number of bytes = 0..3 for 1..4 bytes, should be decremented by 1
    nwbytes--;
    nwbytes &= 3;

    // clear the LSBit of the slave address
    wdata  = slv_addr & 0xFE;
    // command NULL is for normal read/write transaction
    // read or write depends on the slave address bit 0
    wdata |= (uint32_t) I2C_CMD_NULL << I2C_BIT_CMD;
    // LEN1 is the lenght of the first part of the transaction, here the only one
    wdata |= nwbytes << I2C_BIT_LEN1;

    IO_WRITE(base_a | I2C_OFFS_CMD_STA, wdata);
    // don't wait until ready
    return;
}

// start an i2c read, 1 to 4 bytes
void i2c_start_read(uint32_t slv_addr, int nrbytes)
{
    uint32_t base_a, wdata;

    base_a = I2C_BASE_ADDRESS;

    // the parameter number of bytes = 0..3 for 1..4 bytes, should be decremented by 1
    nrbytes--;
    nrbytes &= 3;

    // set the LSBit for read
    wdata  = (slv_addr & 0xFE) | 1;
    // command NULL is for normal read/write transaction
    // read or write depends on the slave address bit 0
    wdata |= (uint32_t) I2C_CMD_NULL << I2C_BIT_CMD;
    // LEN1 is the lenght of the first part of the transaction, here the only one
    wdata |= nrbytes << I2C_BIT_LEN1;
    // start the transaction
    IO_WRITE(base_a | I2C_OFFS_CMD_STA, wdata);
    // don't wait until ready
    return;
}

// start an i2c write with 1 to 4 bytes, then after repeated start a read with 1 to 4 bytes
void i2c_start_write_read(uint32_t slv_addr, int nwbytes, uint32_t wdata, int nrbytes)
{
    uint32_t base_a;

    base_a = I2C_BASE_ADDRESS;

    // write the output data to the buffer
    IO_WRITE(base_a | I2C_OFFS_WDAT, wdata);

    nwbytes--;
    nrbytes--;
    nwbytes &= 3;
    nrbytes &= 3;

    // first write, therefore clear the slave bit 0
    wdata  = slv_addr & 0xFE;
    // special command for repeated start!
    wdata |= (uint32_t) I2C_CMD_RSTRT << I2C_BIT_CMD;
    // the lenght of the first part of the transaction
    wdata |=  nwbytes << I2C_BIT_LEN1;
    // the lenght of the second part of the transaction
    wdata |=  nrbytes << I2C_BIT_LEN2;
    // start the transactions
    IO_WRITE(base_a | I2C_OFFS_CMD_STA, wdata);
    // don't wait until ready
    return;
}

// check if the corresponding I2C master is not busy
int i2c_check_rdy(void)
{
    uint32_t base_a;

    base_a = I2C_BASE_ADDRESS;
    // return 1 when ready and 0 when busy
    return ( (~(IO_READ(base_a | I2C_OFFS_CMD_STA))) >> I2C_BIT_SM_BUSY) & 1;
}

// wait until the I2C master is ready
// returns 1 when timeout, otherwise 0
int i2c_wait_rdy(void)
{
    uint32_t base_a, rsta, cnt;

    base_a = I2C_BASE_ADDRESS;

    cnt = I2C_TIMEOUT;
    do
    {
        rsta = IO_READ(base_a | I2C_OFFS_CMD_STA);
        cnt--;
    } while ((rsta & I2C_MSK_SM_BUSY) && (cnt > 0) );

    if (cnt) return 1; // timeout
    else     return 0; // normal wait time
}


// reset the state machines in the I2C master
void i2c_reset()
{
    uint32_t base_a;

    base_a = I2C_BASE_ADDRESS;
    IO_WRITE(base_a | I2C_OFFS_CMD_STA, I2C_MSK_RESET);
    return;
}
